# at first, we demo HDF5 framework. More can be added.
name: ci_frameworks

on:
  push:
    paths:
      - "mesonbuild/dependencies/**"
      - "test cases/frameworks/25 hdf5"
      - ".github/workflows/frameworks.yml"
  pull_request:
    paths:
      - "mesonbuild/dependencies/**"
      - "test cases/frameworks/25 hdf5"
      - ".github/workflows/frameworks.yml"

jobs:

  macosHDF5:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install -e .
    - run: brew install pkg-config ninja gcc hdf5
    - run: meson setup "test cases/frameworks/25 hdf5" build
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Log
        path: build/meson-logs/meson-log.txt
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Test
        path: build/meson-logs/testlog.txt
