# at first, we demo HDF5 framework. More can be added.
name: ci_frameworks

on:
  push:
    paths:
      - "mesonbuild/dependencies/**"
      - ".github/workflows/frameworks.yml"
  pull_request:
    paths:
      - "mesonbuild/dependencies/**"
      - ".github/workflows/frameworks.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install -e .
    - run: sudo apt install -yq --no-install-recommends ninja-build g++ gfortran libhdf5-dev
    - run: meson setup "test cases/frameworks/25 hdf5" build
      env:
        FC: gfortran
        CXX: g++
        CC: gcc
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Log
        path: build/meson-logs/meson-log.txt
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Test
        path: build/meson-logs/testlog.txt

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install -e .
    - run: brew install pkg-config ninja gcc hdf5
    - run: meson setup "test cases/frameworks/25 hdf5" build
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Log
        path: build/meson-logs/meson-log.txt
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Test
        path: build/meson-logs/testlog.txt

  windows:
    # as usual, start in MSYS to install packages, then switch to MINGW64 to build.
    if: false
    # MSYS2 GitHub Action is still being developed--appears to have PATH bugs stopping this from working.
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MSYS
    - run: msys2do pacman -S mingw64/mingw-w64-x86_64-ninja mingw64/mingw-w64-x86_64-pkg-config mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-hdf5 --noprogressbar --noconfirm
    - run: set MSYSTEM=MINGW64
    - run: python -m pip install -e .
    - run: meson setup "test cases/frameworks/25 hdf5" build
      env:
        FC: gfortran
        CXX: g++
        CC: gcc
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MSYS_Log
        path: build/meson-logs/meson-log.txt
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MSYS2_Test
        path: build/meson-logs/testlog.txt