name: OS Comp Tests

on: [push, pull_request]

jobs:
  xenial:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Use python 3.7 for postprocessing
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Dependencies
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends python3-setuptools python3-pip g++ gfortran gobjc gobjc++ zlib1g-dev python-dev python3-dev libboost-all-dev
        python -m pip install strip-hints f2format autoflake autopep8
    - name: Remove GitHub boost version
      run: sudo rm -rf /usr/local/share/boost
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v1
    - name: System python version
      run: PATH="/usr/bin:$PATH" python3 --version
    - name: Ninja version
      run: ninja --version
    - name: Postprocess
      run: python postprocess -V --hints --imports --fstrings dist
    - name: Run tests
      run: PATH="/usr/bin:$PATH" python3 dist/run_tests.py
      env:
        CI: '1'
        XENIAL: '1'

  arch:
    name: Arch Linux
    runs-on: ubuntu-latest
    container: mensinda/arch:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: ./run_tests.py
      env:
        CI: '1'
